"""empty message

Revision ID: 17913cc7dc2f
Revises: 795a4df1338a
Create Date: 2019-09-26 21:24:54.417608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17913cc7dc2f'
down_revision = '795a4df1338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectLeaders',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], )
    )
    op.create_table('projectWorkers',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectWorkers')
    op.drop_table('projectLeaders')
    # ### end Alembic commands ###
