"""empty message

Revision ID: 18a9eec678cf
Revises: 7ee3852e4566
Create Date: 2019-10-01 22:24:22.949751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18a9eec678cf'
down_revision = '7ee3852e4566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectLeaders',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_table('projectWorkers',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.drop_table('projectworkers')
    op.drop_table('projectleaders')
    op.create_foreign_key(None, 'project', 'user', ['creatorUserId'], ['id'])
    op.drop_index('name', table_name='project_job')
    op.create_foreign_key(None, 'project_job', 'user', ['creatorUserId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'project', ['projectId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'user', ['workerUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.create_index('name', 'project_job', ['name'], unique=True)
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_table('projectleaders',
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userId', 'projectId'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('projectworkers',
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userId', 'projectId'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('projectWorkers')
    op.drop_table('projectLeaders')
    # ### end Alembic commands ###
