"""empty message

Revision ID: 48d7f1730c87
Revises: dfb33f93b4a0
Create Date: 2019-09-29 21:34:35.534973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48d7f1730c87'
down_revision = 'dfb33f93b4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectLeaders',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_table('projectWorkers',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.drop_table('projectworkers')
    op.drop_table('projectleaders')
    op.add_column('project', sa.Column('createTime', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('creatorUserId', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('dateEnd', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('dateStart', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('description', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'project', 'user', ['creatorUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'description')
    op.drop_column('project', 'dateStart')
    op.drop_column('project', 'dateEnd')
    op.drop_column('project', 'creatorUserId')
    op.drop_column('project', 'createTime')
    op.create_table('projectleaders',
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userId', 'projectId'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('projectworkers',
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('projectId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userId', 'projectId'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('projectWorkers')
    op.drop_table('projectLeaders')
    # ### end Alembic commands ###
