"""empty message

Revision ID: 6bef5f327280
Revises: 
Create Date: 2019-10-02 22:26:44.249566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bef5f327280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dateStart', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=False),
    sa.Column('creatorUserId', sa.Integer(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('isDone', sa.Boolean(), nullable=False),
    sa.Column('doneTime', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('delTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creatorUserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projectLeaders',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_table('projectWorkers',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_table('project_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dateStart', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=False),
    sa.Column('estimatedTime', sa.Float(), nullable=False),
    sa.Column('workerUserId', sa.Integer(), nullable=False),
    sa.Column('parentJobId', sa.Integer(), nullable=True),
    sa.Column('creatorUserId', sa.Integer(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('isDone', sa.Boolean(), nullable=False),
    sa.Column('doneTime', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('delTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creatorUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['workerUserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=30), nullable=False),
    sa.Column('fullName', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('delTime', sa.DateTime(), nullable=True),
    sa.Column('activeJobId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activeJobId'], ['project_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('user_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromUserId', sa.Integer(), nullable=False),
    sa.Column('toUserId', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sentTime', sa.DateTime(), nullable=False),
    sa.Column('readTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fromUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['toUserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message')
    op.drop_table('user')
    op.drop_table('project_job')
    op.drop_table('projectWorkers')
    op.drop_table('projectLeaders')
    op.drop_table('project')
    # ### end Alembic commands ###
