"""empty message

Revision ID: 7ee3852e4566
Revises: 25dbce6457df
Create Date: 2019-10-01 00:17:53.958632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee3852e4566'
down_revision = '25dbce6457df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectLeaders',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_table('projectWorkers',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_foreign_key(None, 'project', 'user', ['creatorUserId'], ['id'])
    op.add_column('project_job', sa.Column('doneTime', sa.DateTime(), nullable=True))
    op.add_column('project_job', sa.Column('isDone', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'project_job', 'user', ['creatorUserId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'user', ['workerUserId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'project', ['projectId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_column('project_job', 'isDone')
    op.drop_column('project_job', 'doneTime')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_table('projectWorkers')
    op.drop_table('projectLeaders')
    # ### end Alembic commands ###
