"""empty message

Revision ID: dcbf48dd916e
Revises: 18a9eec678cf
Create Date: 2019-10-01 22:25:47.660513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbf48dd916e'
down_revision = '18a9eec678cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectLeaders',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_table('projectWorkers',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'projectId')
    )
    op.create_foreign_key(None, 'project', 'user', ['creatorUserId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'project', ['projectId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'user', ['creatorUserId'], ['id'])
    op.create_foreign_key(None, 'project_job', 'user', ['workerUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project_job', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_table('projectWorkers')
    op.drop_table('projectLeaders')
    # ### end Alembic commands ###
